import assert from "node:assert/strict";
import test from "node:test";
import { createApi } from "../src/app.ts";
import type { AutoCommentSettingsRepository } from "../src/auto-comment/repository.ts";
import type { BroadcastOperationRepository, BroadcastOperationView } from "../src/broadcast-operations/repository.ts";
import type { BroadcastSettingsRepository } from "../src/broadcast/repository.ts";
import type { EntitlementRepository } from "../src/entitlements/repository.ts";
import type { PackageRepository } from "../src/packages/repository.ts";

const USER = "11111111-1111-1111-1111-111111111111";
const MATERIAL = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1";
const TARGET = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1";
const OPERATION = "cccccccc-cccc-cccc-cccc-ccccccccccc1";
class EmptyPackages implements PackageRepository { async create(): Promise<never> { throw new Error("unused"); } async publish(): Promise<null> { return null; } async list(): Promise<readonly []> { return []; } }
class EmptyBroadcasts implements BroadcastSettingsRepository { async listMaterials(): Promise<readonly []> { return []; } async createMaterial(): Promise<never> { throw new Error("unused"); } async updateMaterial(): Promise<null> { return null; } async deleteMaterial(): Promise<boolean> { return false; } async listLpmTargets(): Promise<readonly []> { return []; } async createLpmTarget(): Promise<never> { throw new Error("unused"); } async updateLpmTarget(): Promise<null> { return null; } async deleteLpmTarget(): Promise<boolean> { return false; } }
class EmptyAutoComments implements AutoCommentSettingsRepository { async listSettings() { return { accounts: [], divisions: [], channelTargets: [] } as const; } async createDivision(): Promise<never> { throw new Error("unused"); } async updateDivision(): Promise<null> { return null; } async deleteDivision(): Promise<boolean> { return false; } async createKeyword(): Promise<null> { return null; } async deleteKeyword(): Promise<boolean> { return false; } async createTemplate(): Promise<null> { return null; } async updateTemplate(): Promise<null> { return null; } async deleteTemplate(): Promise<boolean> { return false; } async createChannelTarget(): Promise<never> { throw new Error("unused"); } async updateChannelTarget(): Promise<null> { return null; } async deleteChannelTarget(): Promise<boolean> { return false; } async attachChannel(): Promise<"NOT_FOUND"> { return "NOT_FOUND"; } async detachChannel(): Promise<boolean> { return false; } async decideCandidate(): Promise<never> { throw new Error("unused"); } }
class EmptyEntitlements implements EntitlementRepository { async grant(): Promise<never> { throw new Error("unused"); } async list(): Promise<readonly []> { return []; } async extend(): Promise<null> { return null; } async revoke(): Promise<boolean> { return false; } }
const operation: BroadcastOperationView = { id: OPERATION, accountId: "dddddddd-dddd-dddd-dddd-ddddddddddd1", accountMode: "USERBOT", status: "QUEUED", intervalSeconds: 30, material: { id: MATERIAL, kind: "TEXT", text: "promo" }, targets: [{ id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee1", sourceLpmTargetId: TARGET, telegramTargetRef: "@lpm", sequenceNumber: 1, preparationStatus: "QUEUED", deliveryStatus: "PENDING", lastErrorCode: null }] };
class FakeOperations implements BroadcastOperationRepository { private seen = false; async create() { const status = this.seen ? "IDEMPOTENT" as const : "CREATED" as const; this.seen = true; return { status, operation }; } async get({ operationId }: { userId: string; operationId: string }) { return operationId === OPERATION ? operation : null; } }
function app(user: string | null = USER) { return createApi({ packages: new EmptyPackages(), broadcasts: new EmptyBroadcasts(), autoComments: new EmptyAutoComments(), entitlements: new EmptyEntitlements(), broadcastOperations: new FakeOperations(), authorizeAdmin: async () => null, authorizeUser: async () => user ? { id: user } : null }); }
test("broadcast operation creates one idempotent outbox operation with a snapshotted interval", async (t) => { const server = app(); t.after(() => server.close()); const payload = { accountMode: "USERBOT", materialId: MATERIAL, targetIds: [TARGET], idempotencyKey: "request-0001" }; const first = await server.inject({ method: "POST", url: "/v1/broadcast/operations", payload }); const again = await server.inject({ method: "POST", url: "/v1/broadcast/operations", payload }); assert.equal(first.statusCode, 201); assert.equal(first.json().operation.intervalSeconds, 30); assert.equal(again.statusCode, 200); assert.equal(again.json().idempotent, true); });
test("broadcast operation rejects malformed input and hides another user's operation", async (t) => { const server = app(); const anonymous = app(null); t.after(() => server.close()); t.after(() => anonymous.close()); const invalid = await server.inject({ method: "POST", url: "/v1/broadcast/operations", payload: { accountMode: "USERBOT" } }); const absent = await server.inject({ method: "GET", url: "/v1/broadcast/operations/ffffffff-ffff-ffff-ffff-ffffffffffff" }); const denied = await anonymous.inject({ method: "POST", url: "/v1/broadcast/operations", payload: {} }); assert.deepEqual(invalid.json().code, "INVALID_BROADCAST_OPERATION"); assert.deepEqual(absent.json(), { code: "BROADCAST_OPERATION_NOT_FOUND" }); assert.deepEqual(denied.json(), { code: "USER_REQUIRED" }); });
